### ISSUE TITLE
I2C Throws Communication Error After Install

### ISSUE THREAD

**Issue by msi-matthew** [zhaolei/WiringOP#12]
Before installing Wiring Pi I tested a I2C device and it was working well.

After install I am getting a `communication error on send` error.

Does something need to be reconfigured on the I2C channel to restore usability?

**Comment by armen181** [comment]
Pins don't have ESD protection and it possible to burn I2C pins, can you try reinstall system and check if I2C pins work as before,

**Comment by msi-matthew** [comment]
Yes. They connect to the device after a clean install.

**Comment by armen181** [comment]
In which Orange board you use ? do you use Armbian? and also please check i2cdetect work?

**Comment by msi-matthew** [comment]
It is an Orange Pi PC Plus.

Running Armbian the `i2cdetect` never doesn't properly identify the devices.

I'm using an Ubuntu build that is linked from the Orange Pi site, which properly identifies the I2C device, but doesn't work harmoniously with the `Wiring` port.

**Comment by armen181** [comment]
you can try write on Armbian forum, on my side i2cdetect work w/o any problem, and this WirnigOP build too, try old or newer version of Armbian too
